---
- name: install portainer docker app
  ansible.builtin.import_tasks: ../../../server/docker_compose_setup/main.yml
  vars:
    app_name: portainer
    local_docker_path: "{{role_path}}/files/docker/"
